#!/bin/bash

# Update DNS for home IP address
# $1 == hostname to update
# $2 == password for authentication

date

passwd=$2
if [[ -z $passwd ]]; then
	passwd=$(aws ssm get-parameter --with-decryption --name dh-dns-auth --query "Parameter.Value" --output text)
fi

curl -s \
	--data-urlencode "passwd=$passwd" \
	--data-urlencode "host=$1" \
	--data-urlencode "comment=Update for $(date +%Y-%m-%d)" \
	https://angrychimp.net/code/dyndns.php

echo
