#!/bin/bash

# Update DNS for home IP address
# $1 == domain name
# $2 == record to update

date

domain=$1
record=$2

if [[ -z $domain || -z $record ]]; then
	echo "Domain/record are required"
	exit
fi

myip=$(curl -s ifconfig.co)
current=$(dig +noall +answer in A $record.$domain | awk '{print $NF}')

if [[ $current == $myip ]]; then
	echo "Record is current"
	[[ "$FORCEUPDATE" == "true" ]] || exit
fi

zoneid=$(aws route53 list-hosted-zones --query "HostedZones[?Name == '$domain.'].Id" --output text | cut -d'/' -f3)

echo "$zoneid / $record => $myip"

aws route53 change-resource-record-sets --hosted-zone-id $zoneid \
	--change-batch "{\"Comment\": \"Home IP udpate for $(date)\", \"Changes\":[{\"Action\": \"UPSERT\",\"ResourceRecordSet\":{\"Name\":\"$record.$domain\", \"Type\": \"A\", \"TTL\": 3600, \"ResourceRecords\":[{\"Value\": \"$myip\"}]}}]}"

echo
